### ISSUE TITLE
is not clickable at point (243,788) because another element <div id="overlayLoading"> obscures it

### ISSUE THREAD

**Issue by malcomZ** [yhamidullah/alphormdownloader#1]
Bonjour,

lors de l’exécution l'erreur suivante apparaît:

-selenium.common.exceptions.ElementClickInterceptedException: Message: Element <a class="cursor video_plan" href="/tutoriel/PlayVideo?idVideo=15421&idtraining=381"> is not clickable at point (243,788) because another element <div id="overlayLoading"> obscures it

Avez-vous une idée du problème ?

Je pense que c'est dù au fait que certaines vidéos mettent du temps à charger.

Cordialement,

**Comment by yhamidullah** [comment]
Je vais mettre un temps d'attente pour le chargement, pour corriger cela et je te fais un retour rapide.

**Comment by malcomZ** [comment]
Merci beaucoup

**Comment by yhamidullah** [comment]
Je ferme ça tu peux rouvrir en cas d'erreur.

**Comment by malcomZ** [comment]
Je viens de tester,

Cela se reproduit a nouveau mais beaucoup plus tard.

selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <a class="cursor video_plan" data-ajax="true" data-ajax-begin="videoSelected(15519)" data-ajax-loading="#overlayLoading" data-ajax-method="POST" data-ajax-success="myCallbackPlatVideo(data);playThisVideo();" href="/tutoriel/PlayVideo?idVideo=15519&amp;idtraining=381">...</a> is not clickable at point (235, 772). Other element would receive the click: <div id="overlayLoading" style="z-index: 9999; display: block;">...</div>


Et petit problème quand il charge le cours au début dans certain cas il n'a pas tous charger et il crash car il n'a pas put scroll

**Comment by yhamidullah** [comment]
J'ai changé le contenu qu'il doit attendre avant de cliquer et j'ai augmenté le temps d'attente.
PS: Si ce n'est pas que la connexion est trop lente fais moi un petit retour après le test.
Merci.

**Comment by malcomZ** [comment]
Parfait, je test  merci

**Comment by malcomZ** [comment]
Le problème reviens mais tard (3eme formations).

"selenium.common.exceptions.ElementClickInterceptedException: Message: Element <a class="cursor video_plan" href="/tutoriel/PlayVideo?idVideo=15212&idtraining=376"> is not clickable at point (199,848) because another element <div id="overlayLoading"> obscures it"

Pas de problème de connexion

**Comment by malcomZ** [comment]
Bonjour, il y a aussi un probleme si le nom de fichier contiens un '?'
