### ISSUE TITLE
NotADirectoryError

### ISSUE THREAD

**Issue by malcomZ** [yhamidullah/alphormdownloader#2]
Bonjour,

lors de l’exécution l'erreur suivante apparaît:

  File ".\main.py", line 96, in get_course
    os.mkdir(course_name + "/" +chapter)
NotADirectoryError: [WinError 267] Nom de répertoire non valide: 'excel-2016-niveau-expert-2-2/12. Les macros : initiation'

avez-vous une idée de comment corriger ?

**Comment by yhamidullah** [comment]
Je fais un patch avec la correction de l'autre erreur.
Merci.

**Comment by malcomZ** [comment]
Merci beaucoup
